name: Description Content 

on:
  pull_request:

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description Content
        run: |
          if echo jq -r .pull_request.body < "$GITHUB_EVENT_PATH" | grep -qP "(?<=## Description\n)(.|\n)*(?=\n##)" ; then
            echo "The 'Description' section is filled."
          else
            echo "The 'Description' section is not filled."
            exit 1
          fi
