name: E2E Test
on:
  pull_request:
    branches:
      - main

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            app/app.go
            app/upgrades/*
            go.mod
            go.sum
            *.toml
            tests/e2e/*
            Dockerfile
            .github/workflows/e2e-test*
      - name: Test E2E
        run: |
          make test-e2e
        if: env.GIT_DIFF
  test-nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: evmosd
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"    
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
            *.toml
            tests/nix_tests/**
            .github/workflows/e2e-test*
      - name: Build nix environment
        run: nix-shell ./tests/nix_tests/shell.nix
        if: env.GIT_DIFF          
  test-nix:
    runs-on: ubuntu-latest
    needs: [test-nix-build]
    strategy:
      matrix:
        test_files: [
          "test_filters.py",
          "test_account.py",
          "test_fee_history.py",
          "test_grpc_only.py",
          "test_ibc.py",
          "test_no_abci_resp.py",
          "test_osmosis_outpost.py",
          "test_precompiles.py",
          "test_priority.py",
          "test_pruned_node.py",
          "test_rollback.py",
          "test_stride_outpost.py",
          "test_storage_proof.py",
          "test_zero_fee.py",
        ]    
    steps:
      - uses: actions/checkout@v4
        # TODO: create a new PAT to use here
        # with:
        #   token: ${{ secrets.E2E_PAT }}              
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
            *.toml
            tests/nix_tests/**
            .github/workflows/e2e-test*
      - name: Setup Nix environment
        run: |
          export PATH=$HOME/.nix-profile/bin:$PATH            
      - name: Run nix tests
        run: make run-nix-tests ${{ matrix.test_files }}
        if: env.GIT_DIFF
      # Commit gomod2nix changes files back to the repository if necessary
      # TODO: uncomment this once added the new PAT to commit the changes (when needed)
      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: update gomod2nix.toml file
      #     file_pattern: '*.toml'

  upload-cache:
    if: github.event_name == 'push'
    needs: ["test-nix"]
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4   
      - uses: cachix/install-nix-action@v25
        with:
          # pin to nix-2.13 to workaround compability issue of 2.14,
          # see: https://github.com/cachix/install-nix-action/issues/161
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: evmosd
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: 'instantiate nix test env'
        run: nix-store -r "$(nix-instantiate tests/nix_tests/shell.nix)"        
